QBCore.Shared.Vehicles = {
    ['gb811s2'] = {
        ['name'] = '811 S2',
        ['brand'] = 'Pfister',
        ['model'] = 'gb811s2',
        ['price'] = 5000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `gb811s2`,
        ['shop'] = 'pdm',
    },
    ['gbadmiral'] = {
        ['name'] = 'Admiral',
        ['brand'] = 'Dundreary',
        ['model'] = 'gbadmiral',
        ['price'] = 5000,
        ['category'] = 'sedans',
        ['categoryLabel'] = 'Sedans',
        ['hash'] = `gbadmiral`,
        ['shop'] = 'pdm',
    },
    ['gbargento7f'] = {
        ['name'] = 'Argento 7F',
        ['brand'] = 'Obey',
        ['model'] = 'gbargento7f',
        ['price'] = 5000,
        ['category'] = 'sedans',
        ['categoryLabel'] = 'Sedans',
        ['hash'] = `gbargento7f`,
        ['shop'] = 'pdm',
    },
    ['gbbanshees'] = {
        ['name'] = 'Banshee S',
        ['brand'] = 'Bravado',
        ['model'] = 'gbbanshees',
        ['price'] = 5000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `gbbanshees`,
        ['shop'] = 'pdm',
    },
    ['gbbisonhf'] = {
        ['name'] = 'Bison HF',
        ['brand'] = 'Bravado',
        ['model'] = 'gbbisonhf',
        ['price'] = 5000,
        ['category'] = 'offroad',
        ['categoryLabel'] = 'Offroad',
        ['hash'] = `gbbisonhf`,
        ['shop'] = 'pdm',
    },
    ['gbbisonstx'] = {
        ['name'] = 'Bison STX',
        ['brand'] = 'Bravado',
        ['model'] = 'gbbisonstx',
        ['price'] = 5000,
        ['category'] = 'vans',
        ['categoryLabel'] = 'Vans',
        ['hash'] = `gbbisonstx`,
        ['shop'] = 'pdm',
    },
    ['gbboxboy'] = {
        ['name'] = 'Boxboy',
        ['brand'] = 'Brute',
        ['model'] = 'gbboxboy',
        ['price'] = 5000,
        ['category'] = 'vans',
        ['categoryLabel'] = 'Vans',
        ['hash'] = `gbboxboy`,
        ['shop'] = 'pdm',
    },
    ['gbboxboyft'] = {
        ['name'] = 'Boxboy Food Truck',
        ['brand'] = 'Brute',
        ['model'] = 'gbboxboyft',
        ['price'] = 5000,
        ['category'] = 'vans',
        ['categoryLabel'] = 'Vans',
        ['hash'] = `gbboxboyft`,
        ['shop'] = 'pdm',
    },
    ['gbbriosof'] = {
        ['name'] = 'Brioso Fulmine',
        ['brand'] = 'Grotti',
        ['model'] = 'gbbriosof',
        ['price'] = 5000,
        ['category'] = 'compacts',
        ['categoryLabel'] = 'Compacts',
        ['hash'] = `gbbriosof`,
        ['shop'] = 'pdm',
    },
    ['gbclubxr'] = {
        ['name'] = 'Club XR',
        ['brand'] = 'BF',
        ['model'] = 'gbclubxr',
        ['price'] = 5000,
        ['category'] = 'compacts',
        ['categoryLabel'] = 'Compacts',
        ['hash'] = `gbclubxr`,
        ['shop'] = 'pdm',
    },
    ['gbcometcl'] = {
        ['name'] = 'Comet Classic',
        ['brand'] = 'Pfister',
        ['model'] = 'gbcometcl',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbcometcl`,
        ['shop'] = 'pdm',
    },
    ['gbcomets1t'] = {
        ['name'] = 'Comet S1 Turbo',
        ['brand'] = 'Pfister',
        ['model'] = 'gbcomets1t',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbcomets1t`,
        ['shop'] = 'pdm',
    },
    ['gbcomets2r'] = {
        ['name'] = 'Comet S2R',
        ['brand'] = 'Pfister',
        ['model'] = 'gbcomets2r',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbcomets2r`,
        ['shop'] = 'pdm',
    },
    ['gbcomets2rc'] = {
        ['name'] = 'Comet S2R C',
        ['brand'] = 'Pfister',
        ['model'] = 'gbcomets2rc',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbcomets2rc`,
        ['shop'] = 'pdm',
    },
    ['gbdominatorgsx'] = {
        ['name'] = 'Dominator GSX',
        ['brand'] = 'Vapid',
        ['model'] = 'gbdominatorgsx',
        ['price'] = 5000,
        ['category'] = 'muscle',
        ['categoryLabel'] = 'Muscle',
        ['hash'] = `gbdominatorgsx`,
        ['shop'] = 'pdm',
    },
    ['gbemerussb1'] = {
        ['name'] = 'Emerus SB1',
        ['brand'] = 'Progen',
        ['model'] = 'gbemerussb1',
        ['price'] = 5000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `gbemerussb1`,
        ['shop'] = 'pdm',
    },
    ['gbeon'] = {
        ['name'] = 'Eon',
        ['brand'] = 'Coil',
        ['model'] = 'gbeon',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbeon`,
        ['shop'] = 'pdm',
    },
    ['gbesperta'] = {
        ['name'] = 'Esperta',
        ['brand'] = 'Bravado',
        ['model'] = 'gbesperta',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbesperta`,
        ['shop'] = 'pdm',
    },
    ['gbgresleystx'] = {
        ['name'] = 'Gresley STX',
        ['brand'] = 'Bravado',
        ['model'] = 'gbgresleystx',
        ['price'] = 5000,
        ['category'] = 'suvs',
        ['categoryLabel'] = 'Suvs',
        ['hash'] = `gbgresleystx`,
        ['shop'] = 'pdm',
    },
    ['gbhades'] = {
        ['name'] = 'Hades',
        ['brand'] = 'Dundreary',
        ['model'] = 'gbhades',
        ['price'] = 5000,
        ['category'] = 'sedans',
        ['categoryLabel'] = 'Sedans',
        ['hash'] = `gbhades`,
        ['shop'] = 'pdm',
    },
    ['gbharmann'] = {
        ['name'] = 'Harmann',
        ['brand'] = 'Benefactor',
        ['model'] = 'gbharmann',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbharmann`,
        ['shop'] = 'pdm',
    },
    ['gbimpaler'] = {
        ['name'] = 'Imapaler',
        ['brand'] = 'Declasse',
        ['model'] = 'gbimpaler',
        ['price'] = 5000,
        ['category'] = 'muscle',
        ['categoryLabel'] = 'Muscle',
        ['hash'] = `gbimpaler`,
        ['shop'] = 'pdm',
    },
    ['gbirisz'] = {
        ['name'] = 'Iris Z',
        ['brand'] = 'Bollokan',
        ['model'] = 'gbirisz',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbirisz`,
        ['shop'] = 'pdm',
    },
    ['gbissimetro'] = {
        ['name'] = 'Issi Metro',
        ['brand'] = 'Weeny',
        ['model'] = 'gbissimetro',
        ['price'] = 5000,
        ['category'] = 'compacts',
        ['categoryLabel'] = 'Compacts',
        ['hash'] = `gbissimetro`,
        ['shop'] = 'pdm',
    },
    ['gbkomodagt'] = {
        ['name'] = 'Komoda GT',
        ['brand'] = 'Lampadati',
        ['model'] = 'gbkomodagt',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbkomodagt`,
        ['shop'] = 'pdm',
    },
    ['gblod4'] = {
        ['name'] = 'LOD 4',
        ['brand'] = 'Coil',
        ['model'] = 'gblod4',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gblod4`,
        ['shop'] = 'pdm',
    },
    ['gbmilano'] = {
        ['name'] = 'Milano',
        ['brand'] = 'Grotti',
        ['model'] = 'gbmilano',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbmilano`,
        ['shop'] = 'pdm',
    },
    ['gbmogulrs'] = {
        ['name'] = 'Mogul RS',
        ['brand'] = 'Karin',
        ['model'] = 'gbmogulrs',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbmogulrs`,
        ['shop'] = 'pdm',
    },
    ['gbmojave'] = {
        ['name'] = 'Mojave',
        ['brand'] = 'Karin',
        ['model'] = 'gbmojave',
        ['price'] = 5000,
        ['category'] = 'offroad',
        ['categoryLabel'] = 'Offroad',
        ['hash'] = `gbmojave`,
        ['shop'] = 'pdm',
    },
    ['gbneonct'] = {
        ['name'] = 'Neon CT',
        ['brand'] = 'Pfister',
        ['model'] = 'gbneonct',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbneonct`,
        ['shop'] = 'pdm',
    },
    ['gbnexusrr'] = {
        ['name'] = 'Nesus RR',
        ['brand'] = 'Dinka',
        ['model'] = 'gbnexusrr',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbnexusrr`,
        ['shop'] = 'pdm',
    },
    ['gbprospero'] = {
        ['name'] = 'Prospero',
        ['brand'] = 'Pegassi',
        ['model'] = 'gbprospero',
        ['price'] = 5000,
        ['category'] = 'super',
        ['categoryLabel'] = 'Super',
        ['hash'] = `gbprospero`,
        ['shop'] = 'pdm',
    },
    ['gbraidillon'] = {
        ['name'] = 'Raidillon',
        ['brand'] = 'Toundra',
        ['model'] = 'gbraidillon',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbraidillon`,
        ['shop'] = 'pdm',
    },
    ['gbronin'] = {
        ['name'] = 'Ronin',
        ['brand'] = 'Emperor',
        ['model'] = 'gbronin',
        ['price'] = 5000,
        ['category'] = 'sedans',
        ['categoryLabel'] = 'Sedans',
        ['hash'] = `gbronin`,
        ['shop'] = 'pdm',
    },
    ['gbsapphire'] = {
        ['name'] = 'Sapphire',
        ['brand'] = 'Enus',
        ['model'] = 'gbsapphire',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbsapphire`,
        ['shop'] = 'pdm',
    },
    ['gbschlagenr'] = {
        ['name'] = 'Schlagen-R',
        ['brand'] = 'Benefactor',
        ['model'] = 'gbschlagenr',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbschlagenr`,
        ['shop'] = 'pdm',
    },
    ['gbschlagensp'] = {
        ['name'] = 'Schlagen-SP',
        ['brand'] = 'Benefactor',
        ['model'] = 'gbschlagensp',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbschlagensp`,
        ['shop'] = 'pdm',
    },
    ['gbschrauber'] = {
        ['name'] = 'Schrauber',
        ['brand'] = 'Benefactor',
        ['model'] = 'gbschrauber',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbschrauber`,
        ['shop'] = 'pdm',
    },
    ['gbschwartzers'] = {
        ['name'] = 'Schwartzer S',
        ['brand'] = 'Benefactor',
        ['model'] = 'gbschwartzers',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbschwartzers`,
        ['shop'] = 'pdm',
    },
    ['gbsentinelgts'] = {
        ['name'] = 'Senrinel GTS',
        ['brand'] = 'Ubermacht',
        ['model'] = 'gbsentinelgts',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbsentinelgts`,
        ['shop'] = 'pdm',
    },
    ['gbsidewinder'] = {
        ['name'] = 'Sidewinder',
        ['brand'] = 'Maxwell',
        ['model'] = 'gbsidewinder',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbsidewinder`,
        ['shop'] = 'pdm',
    },
    ['gbsolace'] = {
        ['name'] = 'Solace',
        ['brand'] = 'Dewbauchee',
        ['model'] = 'gbsolace',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbsolace`,
        ['shop'] = 'pdm',
    },
    ['gbsolacev'] = {
        ['name'] = 'Solace Vitesse',
        ['brand'] = 'Dewbauchee',
        ['model'] = 'gbsolacev',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbsolacev`,
        ['shop'] = 'pdm',
    },
    ['gbstanierle'] = {
        ['name'] = 'Stainer LE',
        ['brand'] = 'Vapid',
        ['model'] = 'gbstanierle',
        ['price'] = 5000,
        ['category'] = 'sedans',
        ['categoryLabel'] = 'Sedans',
        ['hash'] = `gbstanierle`,
        ['shop'] = 'pdm',
    },
    ['gbstarlight'] = {
        ['name'] = 'Starlight',
        ['brand'] = 'Vulcar',
        ['model'] = 'gbstarlight',
        ['price'] = 5000,
        ['category'] = 'sedans',
        ['categoryLabel'] = 'Sedans',
        ['hash'] = `gbstarlight`,
        ['shop'] = 'pdm',
    },
    ['gbsultanrsx'] = {
        ['name'] = 'Sultan RSX',
        ['brand'] = 'Karin',
        ['model'] = 'gbsultanrsx',
        ['price'] = 5000,
        ['category'] = 'sports',
        ['categoryLabel'] = 'Sports',
        ['hash'] = `gbsultanrsx`,
        ['shop'] = 'pdm',
    },
    ['gbtahomagt'] = {
        ['name'] = 'Tahoma GT',
        ['brand'] = 'Declasse',
        ['model'] = 'gbtahomagt',
        ['price'] = 5000,
        ['category'] = 'muscle',
        ['categoryLabel'] = 'Muscle',
        ['hash'] = `gbtahomagt`,
        ['shop'] = 'pdm',
    },
    ['gbtaxiargento7f'] = {
        ['name'] = 'Argento 7F Taxi',
        ['brand'] = 'Obey',
        ['model'] = 'gbtaxiargento7f',
        ['price'] = 5000,
        ['category'] = 'service',
        ['categoryLabel'] = 'Service',
        ['hash'] = `gbtaxiargento7f`,
        ['shop'] = 'pdm',
    },
    ['gbtaxieon'] = {
        ['name'] = 'Eon Taxi',
        ['brand'] = 'Coil',
        ['model'] = 'gbtaxieon',
        ['price'] = 5000,
        ['category'] = 'service',
        ['categoryLabel'] = 'Service',
        ['hash'] = `gbtaxieon`,
        ['shop'] = 'pdm',
    },
    ['gbtaxistanierle'] = {
        ['name'] = 'Stainer LE Taxi',
        ['brand'] = 'Vapid',
        ['model'] = 'gbtaxistanierle',
        ['price'] = 5000,
        ['category'] = 'service',
        ['categoryLabel'] = 'Service',
        ['hash'] = `gbtaxistanierle`,
        ['shop'] = 'pdm',
    },
    ['gbtaxistarlight'] = {
        ['name'] = 'Starlight Taxi',
        ['brand'] = 'Vulcar',
        ['model'] = 'gbtaxistarlight',
        ['price'] = 5000,
        ['category'] = 'service',
        ['categoryLabel'] = 'Service',
        ['hash'] = `gbtaxistarlight`,
        ['shop'] = 'pdm',
    },
    ['gbvoyager'] = {
        ['name'] = 'Voyager 6x4-T',
        ['brand'] = 'MTL',
        ['model'] = 'gbvoyager',
        ['price'] = 5000,
        ['category'] = 'commercial',
        ['categoryLabel'] = 'Commercial',
        ['hash'] = `gbvoyager`,
        ['shop'] = 'pdm',
    },
    ['gbvoyager2'] = {
        ['name'] = 'Voyager 4x2-T',
        ['brand'] = 'MTL',
        ['model'] = 'gbvoyager2',
        ['price'] = 5000,
        ['category'] = 'commercial',
        ['categoryLabel'] = 'Commercial',
        ['hash'] = `gbvoyager2`,
        ['shop'] = 'pdm',
    },
    ['gbvoyagerb'] = {
        ['name'] = 'Voyager 6x4-B',
        ['brand'] = 'MTL',
        ['model'] = 'gbvoyagerb',
        ['price'] = 5000,
        ['category'] = 'commercial',
        ['categoryLabel'] = 'Commercial',
        ['hash'] = `gbvoyagerb`,
        ['shop'] = 'pdm',
    },
    ['gbvoyagerb2'] = {
        ['name'] = 'Voyager 4x2-B',
        ['brand'] = 'MTL',
        ['model'] = 'gbvoyagerb2',
        ['price'] = 5000,
        ['category'] = 'commercial',
        ['categoryLabel'] = 'Commercial',
        ['hash'] = `gbvoyagerb2`,
        ['shop'] = 'pdm',
    },
    ['gbvoyagerg'] = {
        ['name'] = 'Voyager Trash Truck',
        ['brand'] = 'MTL',
        ['model'] = 'gbvoyagerg',
        ['price'] = 5000,
        ['category'] = 'commercial',
        ['categoryLabel'] = 'Commercial',
        ['hash'] = `gbvoyagerg`,
        ['shop'] = 'pdm',
    },
    ['gbvoyagerh'] = {
        ['name'] = 'Voyager 6x2-H',
        ['brand'] = 'MTL',
        ['model'] = 'gbvoyagerh',
        ['price'] = 5000,
        ['category'] = 'commercial',
        ['categoryLabel'] = 'Commercial',
        ['hash'] = `gbvoyagerh`,
        ['shop'] = 'pdm',
    },
    ['gbemsbisonstx'] = {
        ['name'] = 'Bison STX Ambulance',
        ['brand'] = 'Bravado',
        ['model'] = 'gbemsbisonstx',
        ['price'] = 5000,
        ['category'] = 'emergency',
        ['categoryLabel'] = 'Emergency',
        ['hash'] = `gbemsbisonstx`,
        ['shop'] = 'pdm',
    },
    ['gbemsesperta'] = {
        ['name'] = 'Esperta Ambulance',
        ['brand'] = 'Bravado',
        ['model'] = 'gbemsesperta',
        ['price'] = 5000,
        ['category'] = 'emergency',
        ['categoryLabel'] = 'Emergency',
        ['hash'] = `gbemsesperta`,
        ['shop'] = 'pdm',
    },
    ['gbfirevoyager'] = {
        ['name'] = 'Voyager Fire Truck',
        ['brand'] = 'MTL',
        ['model'] = 'gbfirevoyager',
        ['price'] = 5000,
        ['category'] = 'emergency',
        ['categoryLabel'] = 'Emergency',
        ['hash'] = `gbfirevoyager`,
        ['shop'] = 'pdm',
    },
    ['gbpolbisonhf'] = {
        ['name'] = 'Bison HF Police',
        ['brand'] = 'Bravado',
        ['model'] = 'gbpolbisonhf',
        ['price'] = 5000,
        ['category'] = 'emergency',
        ['categoryLabel'] = 'Emergency',
        ['hash'] = `gbpolbisonhf`,
        ['shop'] = 'pdm',
    },
    ['gbpolbisonstx'] = {
        ['name'] = 'Bison STX Police',
        ['brand'] = 'Bravado',
        ['model'] = 'gbpolbisonstx',
        ['price'] = 5000,
        ['category'] = 'emergency',
        ['categoryLabel'] = 'Emergency',
        ['hash'] = `gbpolbisonstx`,
        ['shop'] = 'pdm',
    },
    ['gbpolcometcl'] = {
        ['name'] = 'Comet Classic Police',
        ['brand'] = 'Pfister',
        ['model'] = 'gbpolcometcl',
        ['price'] = 5000,
        ['category'] = 'emergency',
        ['categoryLabel'] = 'Emergency',
        ['hash'] = `gbpolcometcl`,
        ['shop'] = 'pdm',
    },
    ['gbpolcomets2r'] = {
        ['name'] = 'Comet S2R Police',
        ['brand'] = 'Pfister',
        ['model'] = 'gbpolcomets2r',
        ['price'] = 5000,
        ['category'] = 'emergency',
        ['categoryLabel'] = 'Emergency',
        ['hash'] = `gbpolcomets2r`,
        ['shop'] = 'pdm',
    },
    ['gbpoldominatorgsx'] = {
        ['name'] = 'Dominator GSX Police',
        ['brand'] = 'Vapid',
        ['model'] = 'gbpoldominatorgsx',
        ['price'] = 5000,
        ['category'] = 'emergency',
        ['categoryLabel'] = 'Emergency',
        ['hash'] = `gbpoldominatorgsx`,
        ['shop'] = 'pdm',
    },
    ['gbpolprospero'] = {
        ['name'] = 'Prospero Police',
        ['brand'] = 'Pegassi',
        ['model'] = 'gbpolprospero',
        ['price'] = 5000,
        ['category'] = 'emergency',
        ['categoryLabel'] = 'Emergency',
        ['hash'] = `gbpolprospero`,
        ['shop'] = 'pdm',
    },
    ['gbpolsolace'] = {
        ['name'] = 'Solace Police',
        ['brand'] = 'Dewbauchee',
        ['model'] = 'gbpolsolace',
        ['price'] = 5000,
        ['category'] = 'emergency',
        ['categoryLabel'] = 'Emergency',
        ['hash'] = `gbpolsolace`,
        ['shop'] = 'pdm',
    },
    ['gbpolstanierle'] = {
        ['name'] = 'Stainer LE Police',
        ['brand'] = 'Vapid',
        ['model'] = 'gbpolstanierle',
        ['price'] = 5000,
        ['category'] = 'emergency',
        ['categoryLabel'] = 'Emergency',
        ['hash'] = `gbpolstanierle`,
        ['shop'] = 'pdm',
    },
    ['gbpolstarlight'] = {
        ['name'] = 'Starlight Police',
        ['brand'] = 'Vulcar',
        ['model'] = 'gbpolstarlight',
        ['price'] = 5000,
        ['category'] = 'emergency',
        ['categoryLabel'] = 'Emergency',
        ['hash'] = `gbpolstarlight`,
        ['shop'] = 'pdm',
    },
    ['gbpolsultanrsx'] = {
        ['name'] = 'Sultan RSX Police',
        ['brand'] = 'Karin',
        ['model'] = 'gbpolsultanrsx',
        ['price'] = 5000,
        ['category'] = 'emergency',
        ['categoryLabel'] = 'Emergency',
        ['hash'] = `gbpolsultanrsx`,
        ['shop'] = 'pdm',
    },
    ['gbpoltahomagt'] = {
        ['name'] = 'Tahoma GT Police',
        ['brand'] = 'Declasse',
        ['model'] = 'gbpoltahomagt',
        ['price'] = 5000,
        ['category'] = 'emergency',
        ['categoryLabel'] = 'Emergency',
        ['hash'] = `gbpoltahomagt`,
        ['shop'] = 'pdm',
    },
    ['gbpoltr3s'] = {
        ['name'] = 'TR3-S Police',
        ['brand'] = 'Progen',
        ['model'] = 'gbpoltr3s',
        ['price'] = 5000,
        ['category'] = 'emergency',
        ['categoryLabel'] = 'Emergency',
        ['hash'] = `gbpoltr3s`,
        ['shop'] = 'pdm',
    },
    ['gbpolturismogt'] = {
        ['name'] = 'Turismo GT Police',
        ['brand'] = 'Grotti',
        ['model'] = 'gbpolturismogt',
        ['price'] = 5000,
        ['category'] = 'emergency',
        ['categoryLabel'] = 'Emergency',
        ['hash'] = `gbpolturismogt`,
        ['shop'] = 'pdm',
    },
}